t

diff --git a/scripts/qd b/scripts/qd
--- a/scripts/qd
+++ b/scripts/qd
@@ -19,27 +19,30 @@ findroot () {
     fi
 
     CURDIR=`pwd`
-    LOOKUPPATH=".qdenv"
+    ENVFILENAME=".qdenv"
     dir_changed=false
     while [[ `pwd` != "/" ]]
     do
-        if [ -f $LOOKUPPATH ]
+        if [ -f $ENVFILENAME ]
         then
                 if [ "$dir_changed" = true ] ; then
-                    echo "${SECOND_FG}$LOOKUPPATH found: `pwd`${NC_COLOR}" >&2
+                    echo "${SECOND_FG}$ENVFILENAME found: `pwd`${NC_COLOR}" >&2
                 fi
                 LOCAL_PROJECT_ROOT=$(pwd)
-                source $LOOKUPPATH
-
+                source $ENVFILENAME
                 if [ "$LOCAL_PROJECT_ROOT" != $(pwd) ] ; then
                     echo "${SECOND_FG}Project root: $LOCAL_PROJECT_ROOT${NC_COLOR}" >&2
+                    [ -f "${LOCAL_PROJECT_ROOT}/${ENVFILENAME}" ] && source "${LOCAL_PROJECT_ROOT}/${ENVFILENAME}"
+                fi
+                if [ ! -d "${LOCAL_PROJECT_ROOT}/src/" ]; then
+                    LOCAL_PROJECT_ROOT=""
                 fi
                 return
         fi
         dir_changed=true
         cd ..
     done
-    echo "$LOOKUPPATH not found!" >&2
+    echo "$ENVFILENAME not found!" >&2
     exit 1
 }
 
@@ -49,8 +52,8 @@ PROJECT_SUFFIX=${PROJECT_SUFFIX:-"$(echo ${LOCAL_PROJECT_ROOT} | grep -oE "Click
 BUILD_TYPE=${BUILD_TYPE:-debug}
 REMOTE_BUILD_ROOT=${REMOTE_BUILD_ROOT:-"~/build${PROJECT_SUFFIX}"}
 REMOTE_DATA_ROOT=${REMOTE_DATA_ROOT:-${REMOTE_BUILD_ROOT}/_data}
-REMOTE_SOURCE_ROOT=${REMOTE_SOURCE_ROOT:-"/Users/vdimir/ClickHouse${PROJECT_SUFFIX}"}
-REMOTE_LOG_FILENAME=${REMOTE_LOG_FILENAME:-_server.log}
+REMOTE_SOURCE_ROOT=${REMOTE_SOURCE_ROOT:-"~/sources/ClickHouse${PROJECT_SUFFIX}"}
+REMOTE_LOG_FOLDER=${REMOTE_LOG_FOLDER:-"~/logs"}
 
 COMMAND_NAME=$(basename $0)
 
@@ -100,10 +103,8 @@ sub_info(){
     echo "REMOTE_BUILD_ROOT=${REMOTE_BUILD_ROOT}"
     echo "REMOTE_DATA_ROOT=${REMOTE_DATA_ROOT}"
     echo "REMOTE_SOURCE_ROOT=${REMOTE_SOURCE_ROOT}"
-    echo "REMOTE_LOG_FILENAME=${REMOTE_LOG_FILENAME}"
-    echo "Builds: "
-    ssh -tt $DEVSERV "du -sh ${REMOTE_BUILD_ROOT}/*"
-
+    echo "REMOTE_LOG_FOLDER=${REMOTE_LOG_FOLDER}"
+    ssh -tt $DEVSERV 'echo "----- `hostname` -----";' "du -sh ${REMOTE_BUILD_ROOT}/*;"
 }
 
 sub_zshcompletion(){
@@ -119,6 +120,7 @@ sub_zshcompletion(){
 sub_forward_port(){
     sub_forward_port_down || echo 'not forwarding ...'
     ssh -fNTML 9000:localhost:9000 $DEVSERV
+    ssh -fNTML 8123:localhost:8123 $DEVSERV
 }
 
 sub_forward_port_check(){
@@ -129,21 +131,28 @@ sub_forward_port_down(){
     ssh -TO exit $DEVSERV
 }
 
-sub_synctest(){
+check_local_src_copy(){
+    if [ -z ${LOCAL_PROJECT_ROOT} ]; then
+        echo "No local source copy!"
+        return 0
+    fi
+
     if [ ! -d "${LOCAL_PROJECT_ROOT}/src/" ]; then
         echo "Cannot find src directory"
         exit 1
     fi
+    return 1
+}
+
+sub_synctest(){
+    check_local_src_copy && return
 
     set -x
     rsync ${1:-} -rvP --checksum -e ssh "${LOCAL_PROJECT_ROOT}/tests/" $DEVSERV:"${REMOTE_SOURCE_ROOT}/tests" | grep -v 'skipping non-regular file'
 }
 
 sub_syncall(){
-    if [ ! -d "${LOCAL_PROJECT_ROOT}/src/" ]; then
-        echo "Cannot find src directory"
-        exit 1
-    fi
+    check_local_src_copy && return
 
     set -x
     rsync ${1:-} -rvP --checksum -e ssh "${LOCAL_PROJECT_ROOT}/docker/" $DEVSERV:"${REMOTE_SOURCE_ROOT}/docker"  | grep -v 'skipping non-regular file'
@@ -157,14 +166,14 @@ sub_syncall(){
 
 sub_sync(){
     echo "${BLUE_FG}Building directory ${REMOTE_BUILD_ROOT}/${BUILD_TYPE}${NC_COLOR}" >&2
+    check_local_src_copy && return
 
-    if [ ! -d "${LOCAL_PROJECT_ROOT}/src/" ]; then
-        echo "Cannot find src directory"
-        exit 1
-    fi
     set -x
     rsync ${@:-} -rvP --checksum -e ssh "${LOCAL_PROJECT_ROOT}/src/" $DEVSERV:"${REMOTE_SOURCE_ROOT}/src"
     rsync ${@:-} -rvP --checksum -e ssh "${LOCAL_PROJECT_ROOT}/programs/" $DEVSERV:"${REMOTE_SOURCE_ROOT}/programs"  | grep -v 'skipping non-regular file'
+    rsync ${@:-} -rvP --checksum -e ssh "${LOCAL_PROJECT_ROOT}/base/" $DEVSERV:"${REMOTE_SOURCE_ROOT}/base"  | grep -v 'skipping non-regular file'
+
+
 }
 
 sub_cmake(){
@@ -180,9 +189,9 @@ sub_cmake(){
         ARGS="${ARGS} -DENABLE_CLICKHOUSE_ALL=OFF"
         ARGS="${ARGS} -DENABLE_TESTS=OFF"
         ARGS="${ARGS} -DUSE_UNWIND=ON"
-    else
-        ARGS="${ARGS} -DENABLE_CLICKHOUSE_ALL=ON"
     fi
+
+    # ARGS="${ARGS} -DENABLE_CLICKHOUSE_ALL=ON"
 
     case ${BUILD_TYPE} in
     "reldeb")
@@ -201,16 +210,19 @@ sub_cmake(){
     ;;
     "tsan")
         ARGS="${ARGS} -DCMAKE_BUILD_TYPE=RelWithDebInfo"
-        ARGS="${ARGS} -DSANITIZE=address"
+        ARGS="${ARGS} -DSANITIZE=thread"
     ;;
     "ubsan")
         ARGS="${ARGS} -DCMAKE_BUILD_TYPE=RelWithDebInfo"
         ARGS="${ARGS} -DSANITIZE=undefined"
     ;;
+    "arm")
+        ARGS="${ARGS} -DCMAKE_TOOLCHAIN_FILE=cmake/linux/toolchain-aarch64.cmake"
+    ;;
     *)
         echo "Unknown build type '${BUILD_TYPE}'"
         exit 1
-        ;;
+    ;;
     esac
 
     set -x
@@ -219,9 +231,12 @@ sub_cmake(){
         -DCMAKE_C_COMPILER=\`which clang-${CLANG_VERSION}\` \
         -DCMAKE_CXX_COMPILER=\`which clang++-${CLANG_VERSION}\` \
         ${ARGS}"
+
+    sub_build
 }
 
 sub_build(){
+    set -x
     sub_sync
     if [[ ${1:-""} == "all" ]]; then
         ssh -tt $DEVSERV "ninja -C ${REMOTE_BUILD_ROOT}/${BUILD_TYPE}"
@@ -244,7 +259,7 @@ sub_gdb(){
     if [[ ${1:-""} == "g" ]]; then
         ssh -tt $DEVSERV "mkdir -p ${REMOTE_DATA_ROOT} && cd ${REMOTE_DATA_ROOT} && gdb ${REMOTE_BUILD_ROOT}/${BUILD_TYPE}/programs/clickhouse-server"
     else
-        ssh -tt $DEVSERV "mkdir -p ${REMOTE_DATA_ROOT} && cd ${REMOTE_DATA_ROOT} && lldb-11 ${REMOTE_BUILD_ROOT}/${BUILD_TYPE}/programs/clickhouse-server"
+        ssh -tt $DEVSERV "mkdir -p ${REMOTE_DATA_ROOT} && cd ${REMOTE_DATA_ROOT} && lldb ${REMOTE_BUILD_ROOT}/${BUILD_TYPE}/programs/clickhouse-server"
     fi;
 }
 
@@ -254,14 +269,15 @@ sub_run(){
         ssh -tt $DEVSERV "rm -rf ${REMOTE_DATA_ROOT}"
     fi
 
-    ssh -tt $DEVSERV "mkdir -p ${REMOTE_DATA_ROOT} && cd ${REMOTE_DATA_ROOT} && cp ${REMOTE_LOG_FILENAME} ${REMOTE_LOG_FILENAME}.`date +%Y%m%d_%H%M%S`; echo '' > ${REMOTE_LOG_FILENAME}"
+    ADD_ARGS=""
+    if [[ ${1:-""} == "cfg" ]]; then
+        ADD_ARGS="${ADD_ARGS} --config ~/chcfg/config.xml"
+    fi
+
+    ssh -tt $DEVSERV "mkdir -p ${REMOTE_LOG_FOLDER}; echo '' > ${REMOTE_LOG_FOLDER}/clickhouse-server.log"
     echo "Running ${BLUE_FG}${REMOTE_BUILD_ROOT}/${BUILD_TYPE}${NC_COLOR}/programs/clickhouse-server"
 
-    if [[ ${1:-""} == "cfg" ]]; then
-        ssh -tt $DEVSERV "mkdir -p ${REMOTE_DATA_ROOT} && cd ${REMOTE_DATA_ROOT} && ${REMOTE_BUILD_ROOT}/${BUILD_TYPE}/programs/clickhouse-server -L ${REMOTE_LOG_FILENAME} --config ${REMOTE_SOURCE_ROOT}/programs/server/config.xml"
-    else
-        ssh -tt $DEVSERV "mkdir -p ${REMOTE_DATA_ROOT} && cd ${REMOTE_DATA_ROOT} && ${REMOTE_BUILD_ROOT}/${BUILD_TYPE}/programs/clickhouse-server -L ${REMOTE_LOG_FILENAME}"        
-    fi
+    ssh -tt $DEVSERV "mkdir -p ${REMOTE_DATA_ROOT} && cd ${REMOTE_DATA_ROOT} && ${REMOTE_BUILD_ROOT}/${BUILD_TYPE}/programs/clickhouse-server ${ADD_ARGS}"
 }
 
 sub_brun(){
@@ -281,7 +297,7 @@ sub_rrun(){
          REMOTE_BUILD_ROOT='${REMOTE_BUILD_ROOT}' \
          REMOTE_DATA_ROOT='${REMOTE_DATA_ROOT}' \
          REMOTE_SOURCE_ROOT='${REMOTE_SOURCE_ROOT}' \
-         REMOTE_LOG_FILENAME='${REMOTE_LOG_FILENAME}' \
+         REMOTE_LOG_FOLDER='${REMOTE_LOG_FOLDER}' \
          ${BASH_SOURCE} run"
 }
 
@@ -303,7 +319,7 @@ sub_ps(){
 }
 
 sub_log(){
-    ssh -tt $DEVSERV "cat ${REMOTE_DATA_ROOT}/${REMOTE_LOG_FILENAME}"
+    ssh -tt $DEVSERV "cat ${REMOTE_LOG_FOLDER}/clickhouse-server.log"
 }
 
 sub_dlog(){
@@ -320,9 +336,9 @@ sub_clear(){
 sub_taillog(){
     sub_clear
     if [ ! -z $@ ]; then
-        ssh -tt $DEVSERV "tail -f ${REMOTE_DATA_ROOT}/${REMOTE_LOG_FILENAME} | grep $@"
+        ssh -tt $DEVSERV "tail -f ${REMOTE_LOG_FOLDER}/clickhouse-server.log | grep $@"
     else
-        ssh -tt $DEVSERV "tail -f ${REMOTE_DATA_ROOT}/${REMOTE_LOG_FILENAME}"
+        ssh -tt $DEVSERV "tail -f ${REMOTE_LOG_FOLDER}/clickhouse-server.log"
     fi
 }
 
@@ -356,28 +372,40 @@ ssh_add_github(){
 
 sub_git_status(){
     ssh_add_github
-    ssh -tt $DEVSERV "git -C \"${REMOTE_SOURCE_ROOT}\" log  --abbrev-commit --format='%h (%ar) "%s" %d' -1; git -C \"${REMOTE_SOURCE_ROOT}\" status" 
+    ssh -tt $DEVSERV "git -C ${REMOTE_SOURCE_ROOT} log  --abbrev-commit --format='%h (%ar) "%s" %d' -1; git -C ${REMOTE_SOURCE_ROOT} status" 
 }
 
 sub_git_update(){
     ssh_add_github
-    set -x
-    ssh -tt $DEVSERV "git -C \"${REMOTE_SOURCE_ROOT}\" reset --hard" 
-    ssh -tt $DEVSERV "sudo git -C \"${REMOTE_SOURCE_ROOT}\" clean -fdx"
+
+    ssh -tt $DEVSERV sh <<EOF
+set -x
+[ ! -d ${REMOTE_SOURCE_ROOT} ] \
+    && git clone --recursive git@github.com:vdimir/ClickHouse.git ${REMOTE_SOURCE_ROOT} \
+    && git -C ClickHouse remote add upstream git@github.com:ClickHouse/ClickHouse.git \
+    && git -C ClickHouse fetch origin
+git -C ${REMOTE_SOURCE_ROOT} reset --hard
+sudo git -C ${REMOTE_SOURCE_ROOT} clean -fdx
+exit
+EOF
+
     if [[ ${1:-} == "" ]]; then
-        ssh -tt $DEVSERV "git -C \"${REMOTE_SOURCE_ROOT}\" checkout master" 
+        ssh -tt $DEVSERV "git -C ${REMOTE_SOURCE_ROOT} checkout master" 
     else
-        ssh -tt $DEVSERV "cd \"${REMOTE_SOURCE_ROOT}\" && gh pr checkout ${1} -R ClickHouse/ClickHouse --force" 
+        ssh -tt $DEVSERV "cd ${REMOTE_SOURCE_ROOT} && gh pr checkout ${1} -R ClickHouse/ClickHouse --force" 
     fi
 
-    ssh -tt $DEVSERV "git -C \"${REMOTE_SOURCE_ROOT}\" pull" 
-    ssh -tt $DEVSERV "git -C \"${REMOTE_SOURCE_ROOT}\" sup" 
+    ssh -tt $DEVSERV "git -C ${REMOTE_SOURCE_ROOT} pull && git -C ${REMOTE_SOURCE_ROOT} sup" 
     echo "----------------------"
     sub_git_status
 }
 
 sub_ssh(){
-    TERM=xterm-256color ssh -tA $DEVSERV "cd ${REMOTE_SOURCE_ROOT} ; exec $SHELL"
+    if [[ ${1:-} == "src" ]]; then
+        TERM=xterm-256color ssh -tA $DEVSERV "cd ${REMOTE_SOURCE_ROOT} ; exec $SHELL"
+    else
+        TERM=xterm-256color ssh -tA $DEVSERV
+    fi
 }
 
 sub_exec(){
@@ -390,7 +418,7 @@ sub_getbinary(){
     set -eux
     DOWNLOAD_DIR="~/_tmp"
 
-    ssh $DEVSERV "cat > ${DOWNLOAD_DIR}/dld.sh && chmod +x ${DOWNLOAD_DIR}/dld.sh" << 'EOF'
+    ssh $DEVSERV "mkdir -p ${DOWNLOAD_DIR} && cat > ${DOWNLOAD_DIR}/dld.sh && chmod +x ${DOWNLOAD_DIR}/dld.sh" << 'EOF'
 #!/bin/bash
 
 set -eux
@@ -404,7 +432,7 @@ if [[ $1 == *github.com*clickhouse-common-static*tgz ]]; then
     # mv ${OUT_FILE}/usr/bin/clickhouse ${BASE_FOLDER}/clickhouse-$(echo ${OUT_FILE} | sed -r -e 's!.*clickhouse-(.+)!\1!')
     rm ${OUT_FILE}.tgz
 else
-    OUT_FILE=${BASE_FOLDER}/"clickhouse-$(echo $1 | sed -r -e 's!^.*/([0-9]+)/.*/clang-1[0-9]_([a-z_]+)_bundled.*!\1-\2!')"
+    OUT_FILE=${BASE_FOLDER}/"clickhouse-$(echo $1 | sed -r -e 's!^.*/([0-9]+)/.*_(\w+)/clickhouse!\1-\2!')"
     if [ ! -f ${OUT_FILE} ]; then
         wget "$1" -O ${OUT_FILE}
         chmod +x ${OUT_FILE}
